[build]
  publish = "dist"
  command = "vite build"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev & npm run server"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 